AWSTemplateFormatVersion: '2010-09-09'
Description: Simple Calc web service. State is stored in a DynamoDB table.
Resources:
  CalcGetFunction:
    Properties:
      CodeUri: s3://hpang-sam-bucket/7a41c1xxxxx
      Environment:
        Variables:
          TABLE_NAME:
            Ref: Table
      Events:
        GetResource:
          Properties:
            Method: get
            Path: /calc/{operand1}/{operand2}/{operator}
          Type: Api
      Handler: index.handler
      Policies: AmazonDynamoDBReadOnlyAccess
      Runtime: nodejs4.3
    Type: AWS::Serverless::Function
  Table:
    Properties:
      PrimaryKey:
        Name: calcAnswer
        Type: Number
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
    Type: AWS::Serverless::SimpleTable
Transform: AWS::Serverless-2016-10-31
